---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: jenkins
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "varun000reddy/calculator-miniproject"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
        
    - name: stop container
      shell: docker stop calculator
      
      
    - name: rm container
      shell: docker rm calculator
      
     
    - name: Running container
      shell: docker run -it -d --name calc -p 8083:8082 varun000reddy/calculator-miniproject
